notifications:
  email: false
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
install:
- docker pull $DOCKER_IMAGE
script:
- docker run --rm -v `pwd`:/work $DOCKER_IMAGE $PRE_CMD /work/travis/build-wheels.sh
- ls wheelhouse/
deploy:
  provider: releases
  api_key:
    secure: HLtksRbQ+2BQ+R5b+S+CoXohHGK1Tv1WtNZ0+GCFG+vwNhyovMUBTEUsucbsmR7c0dVU72WiqfYeKWzoqYPWBPy8kY60+HKbUkpmyI/vLlYfsxfym2mwvJJDQqmSMA6nYYcR1TFa40YbGQ1iJJEJ2nU9MBm/P2D5ZCDLm+y8Gz9Y1MbLycqifBDg2J4NFUauUKRZsqE0otEuxUQVBqUklGdClkB0NK4USW1dGynoGVltnLmOVOEBHddpyONe/LIYyQft/sH+unG4Onpgw06TJBnwwjeoetwNOsy5kDqAxBD/QiBcjww1f29bK92e3L088OTUVqD1JnehgS3GvsTq+yySwJiYgJ5l/urX2MYQxkeW6qTYMW1kVG3UuEglhcp9feq2c1e6U8MyKEb9bqR9ue87S/Bm5+3JMDiG7dBf0lPcWld2gbSYv4Q8cfFTnfrZGGsNSnzKOtPxzJ8wq8FT5XweR9vN83nnwn633zEJ4TSyuHzNtvLcmcY0lPenwRwa7K1a5/D97cfyU8V27yoKyYa1QW5ihjt3wewh76zEiURGbd0pGlaDnwI7jjrQ2TSFglgzxR+yae0Bq/Y6PQslv/1RonwrBq75J4S2JR0GMYtTHf5mcM86wjyd5Sa+XKMe+aDBMwtLQVtB2PmgM86iKkaRAjea635dKLkzNCq0Ogk=
  skip_cleanup: true
  file_glob: true
  file: wheelhouse/yahtzeevalue-*.whl
  on:
    repo: Mortal/yahtzeevalue
    tags: true
