[package]
name = "yahtzeevalue"
version = "0.1.0"
authors = ["Mathias Rav <m@git.strova.dk>"]
edition = "2018"

[dependencies]
rand = "0.6"
byteorder = "1.3"
memmap = "0.7"

[lib]
name = "yahtzeevalue"
crate-type = ["cdylib"]
